global:
  podDNSSearchNamespaces:
  - global
  - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"
  multiCluster:
    enabled: true
  controlPlaneSecurityEnabled: true

security:
  selfSigned: false

mtls:
    enabled: false

istiocoredns:
  enabled: true

gateways:
  istio-egressgateway:
    enabled: true
    env:
      ISTIO_META_REQUESTED_NETWORK_VIEW: "external"

sidecarInjectorWebhook:
  enabled: true
  rewriteAppHTTPProbe: false

grafana:
  enabled: true

tracing:
  enabled: true

kiali:
  enabled: true
  dashboard:
    jaegerURL: http://jaeger-query:16686
    grafanaURL: http://grafana:3000

pilot:
  traceSampling: 100.0

mixer:
  policy:
    enabled: true
  telemetry:
    enabled: true
  adapters:
    stdio:
      enabled: true